# Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Debug APK without testOnly, otherwise Studio/adb report that MainActivity does not exist
android.injected.testOnly=false

# Memory
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Suppress false mutation errors in KSP/Compose
android.buildFeatures.buildConfig=true

# Disable KSP incremental compilation to avoid PersistentMap/JavaVersion bug
ksp.incremental=false